### ISSUE TITLE
 ? ImportError: No module named burger_data

### ISSUE THREAD

**Issue by Mepth** [GarethNelson/YATE#1]
Where can I get it?

**Comment by Pokechu22** [comment]
Oh, hey, I'm watching this repo!

[Burger](https://github.com/mcdevs/burger) is a tool that takes MC jars and makes data from it.  For instance, [this page](http://pokechu22.github.io/Burger/1.12.html) is generated from [this data](http://pokechu22.github.io/Burger/1.12.json) from the 1.12 jar.

That said, I'm not aware of a python module for the data itself (while burger is written in python, the output is JSON).

I haven't done too much python recently, but something like this should generate the needed data (not sure what the original one was; also do consider the MC version; I've uploaded burger data for most MC versions but you may need to make it yourself as I don't remember exactly what version YATE was for):

```python
import urllib
try:
    import json
except ImportError:
    import simplejson as json

def read_burger():
    stream = urllib.urlopen("http://pokechu22.github.io/Burger/1.12.json")
    try:
        return json.load(stream)
    finally:
        stream.close()

def make_blockids():
    burger = read_burger()[0]
    blocks = {}
    for block in burger["blocks"]["block"].itervalues():
        blocks[block["numeric_id"]] = block

blockid_blocks = make_blockids()
```

**Comment by GwenNelson** [comment]
Not sure if this is still relevant, but it was sitting around on my local machine not committed to github, it should be there now.

That said, i've pretty much abandoned YATE as i'm busy with other projects, but please let me know if you want to pick up where I left off.
